addons:
  apt:
    packages:
	  - libgtk-3-dev
	  - libevince-dev
	  - libgtksourceview-3.0-dev

script: make -C src

notifications:
  email:
    recipients:
      - ollie.etherington@gmail.com
    on_success: never
    on_failure: always
